### ISSUE TITLE
Parameter to MergeFrom() must be instance of same class

### ISSUE THREAD

**Issue by inoxsss** [EagerAI/kerastuneR#37]
Hi, 
i have issues using the package because I get the following error message 
Has anybody faced it before ?

2021-11-21 00:09:55.106894: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/mng/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/kerastuner/engine/hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/reticulate/python/rpytools/call.py", line 21, in python_function
    raise RuntimeError(res[kErrorKey])
[Warning] Invalid model 0/5
RuntimeError: Evaluation error: TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorflow.TensorShapeProto got tensorflow.TensorShapeProto

**Comment by turgut090** [comment]
Hi, please share a reproducible example / your code

**Comment by inoxsss** [comment]
Hi, please find bellow the code. 
I get the error when I run the "tuner"
Thanks 

library(keras)
library(tensorflow)
use_condaenv(condaenv = "r-tensorflow")
library(kerastuneR)
library(remotes)
library(reticulate)
library(dplyr)
library(reticulate)

kerastuneR::install_kerastuner(python_path ='paste python path')

x_data <- matrix(data = runif(500,0,1),nrow = 50,ncol = 5)
y_data <-  ifelse(runif(50,0,1) > 0.6, 1L,0L) %>% as.matrix()

x_data2 <- matrix(data = runif(500,0,1),nrow = 50,ncol = 5)
y_data2 <-  ifelse(runif(50,0,1) > 0.6, 1L,0L) %>% as.matrix()

build_model = function(hp) {
  model = keras_model_sequential()
  model %>% layer_dense(units = hp$Int('units',
                                       min_value = 32,
                                       max_value = 512,
                                       step=  32),
                                       input_shape = ncol(x_data),
                        activation = 'relu') %>%
    layer_dense(units = 1, activation = 'softmax') %>%
    compile(
      optimizer = tf$keras$optimizers$Adam(
        hp$Choice('learning_rate',
                  values=c(1e-2, 1e-3, 1e-4))),
      loss = 'binary_crossentropy',
      metrics = 'accuracy')
  return(model)
}

tuner = RandomSearch(
        build_model,
        objective = 'val_accuracy',
        max_trials = 5,
        executions_per_trial = 3,
        directory = 'my_dir',
        project_name = 'Hypertuner_ANN')

**Comment by inoxsss** [comment]
its said that this command : pip install -U protobuf
could solve the problem.
Since I'm only using R how can I try the command through R ?

https://deeptalk.lambdalabs.com/t/cant-build-keras-model-after-tensorflow-update-from-2-2-to-2-3/1799/7
Thanks

**Comment by turgut090** [comment]
Which version of TensorFlow and KerasTuner do you have installed in your system?

```
> tensorflow::tf_version()
[1] ‘2.6’
> kerastuneR::keras_tuner_version()
[1] "1.0.1"
```


```
> library(magrittr)
> x_data <- matrix(data = runif(500,0,1),nrow = 50,ncol = 5)
> y_data <-  ifelse(runif(50,0,1) > 0.6, 1L,0L) %>% as.matrix()
> x_data2 <- matrix(data = runif(500,0,1),nrow = 50,ncol = 5)
> y_data2 <-  ifelse(runif(50,0,1) > 0.6, 1L,0L) %>% as.matrix()
> library(keras)
> library(tensorflow)
> library(kerastuneR)
> build_model = function(hp) {
+   
+   model = keras_model_sequential()
+   model %>% layer_dense(units = hp$Int('units',
+                                        min_value = 32,
+                                        max_value = 512,
+                                        step=  32),input_shape = ncol(x_data),
+                         activation =  'relu') %>%
+     layer_dense(units = 1, activation = 'softmax') %>%
+     compile(
+       optimizer = tf$keras$optimizers$Adam(
+         hp$Choice('learning_rate',
+                   values=c(1e-2, 1e-3, 1e-4))),
+       loss = 'binary_crossentropy',
+       metrics = 'accuracy')
+   return(model)
+ }
> tuner = RandomSearch(
+   build_model,
+   objective = 'val_accuracy',
+   max_trials = 5,
+   executions_per_trial = 3,
+   directory = 'my_dir',
+   project_name = 'helloworld')
2021-11-28 11:10:20.135917: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-28 11:10:20.136292: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib:/usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
2021-11-28 11:10:20.136378: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib:/usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
2021-11-28 11:10:20.136455: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib:/usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
2021-11-28 11:10:20.136522: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib:/usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
2021-11-28 11:10:20.136598: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib:/usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
2021-11-28 11:10:20.136667: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib:/usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
2021-11-28 11:10:20.136741: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib:/usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
2021-11-28 11:10:20.136809: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/turgut/.local/share/r-miniconda/envs/r-reticulate/lib:/usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
2021-11-28 11:10:20.136824: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-11-28 11:10:20.137041: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> tuner %>% search_summary()
[Search space summary]
 |-Default search space size: 2
 > units (Int)
 |-default: None
 |-max_value: 512
 |-min_value: 32
 |-sampling: None
 |-step: 32
 > learning_rate (Choice)
 |-default: 0.01
 |-ordered: True
 |-values: [0.01, 0.001, 0.0001]
> tuner %>% fit_tuner(x_data,y_data,
+                     epochs = 5, 
+                     validation_data = list(x_data2,y_data2))
2021-11-28 11:10:28.987090: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/5
2/2 [==============================] - 0s 106ms/step - loss: 0.6796 - accuracy: 0.4600 - val_loss: 0.6730 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6794 - accuracy: 0.4600 - val_loss: 0.6730 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6793 - accuracy: 0.4600 - val_loss: 0.6730 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6792 - accuracy: 0.4600 - val_loss: 0.6730 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6791 - accuracy: 0.4600 - val_loss: 0.6729 - val_accuracy: 0.4200
Epoch 1/5
2/2 [==============================] - 0s 85ms/step - loss: 0.6896 - accuracy: 0.4600 - val_loss: 0.6830 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 20ms/step - loss: 0.6894 - accuracy: 0.4600 - val_loss: 0.6830 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6893 - accuracy: 0.4600 - val_loss: 0.6830 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6893 - accuracy: 0.4600 - val_loss: 0.6830 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6892 - accuracy: 0.4600 - val_loss: 0.6830 - val_accuracy: 0.4200
Epoch 1/5
2/2 [==============================] - 0s 83ms/step - loss: 0.6928 - accuracy: 0.4600 - val_loss: 0.6969 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6925 - accuracy: 0.4600 - val_loss: 0.6969 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6924 - accuracy: 0.4600 - val_loss: 0.6968 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6923 - accuracy: 0.4600 - val_loss: 0.6967 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6922 - accuracy: 0.4600 - val_loss: 0.6966 - val_accuracy: 0.4200
[Trial complete]
[Trial summary]
 |-Trial ID: aa8cf30b255388061196cd66d1193dd3
 |-Score: 0.41999998688697815
 |-Best step: 0
 > Hyperparameters:
 |-learning_rate: 0.0001
 |-units: 64
Epoch 1/5
2/2 [==============================] - 0s 83ms/step - loss: 0.6899 - accuracy: 0.4600 - val_loss: 0.6870 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6874 - accuracy: 0.4600 - val_loss: 0.6843 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6837 - accuracy: 0.4600 - val_loss: 0.6829 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6814 - accuracy: 0.4600 - val_loss: 0.6820 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 11ms/step - loss: 0.6792 - accuracy: 0.4600 - val_loss: 0.6809 - val_accuracy: 0.4200
Epoch 1/5
2/2 [==============================] - 0s 82ms/step - loss: 0.6952 - accuracy: 0.4600 - val_loss: 0.6931 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6903 - accuracy: 0.4600 - val_loss: 0.6900 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6875 - accuracy: 0.4600 - val_loss: 0.6881 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6850 - accuracy: 0.4600 - val_loss: 0.6865 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6827 - accuracy: 0.4600 - val_loss: 0.6854 - val_accuracy: 0.4200
Epoch 1/5
2/2 [==============================] - 0s 85ms/step - loss: 0.6943 - accuracy: 0.4600 - val_loss: 0.6907 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6904 - accuracy: 0.4600 - val_loss: 0.6867 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6879 - accuracy: 0.4600 - val_loss: 0.6835 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 17ms/step - loss: 0.6847 - accuracy: 0.4600 - val_loss: 0.6811 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6833 - accuracy: 0.4600 - val_loss: 0.6792 - val_accuracy: 0.4200
[Trial complete]
[Trial summary]
 |-Trial ID: d571476f33959b80a4c8cde5a4df2196
 |-Score: 0.41999998688697815
 |-Best step: 0
 > Hyperparameters:
 |-learning_rate: 0.001
 |-units: 288
Epoch 1/5
2/2 [==============================] - 0s 84ms/step - loss: 0.7045 - accuracy: 0.4600 - val_loss: 0.6751 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6798 - accuracy: 0.4600 - val_loss: 0.6799 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6670 - accuracy: 0.4600 - val_loss: 0.6786 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6560 - accuracy: 0.4600 - val_loss: 0.6753 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6545 - accuracy: 0.4600 - val_loss: 0.6747 - val_accuracy: 0.4200
Epoch 1/5
2/2 [==============================] - 0s 84ms/step - loss: 0.7236 - accuracy: 0.4600 - val_loss: 0.6756 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6959 - accuracy: 0.4600 - val_loss: 0.6828 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6729 - accuracy: 0.4600 - val_loss: 0.6764 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 14ms/step - loss: 0.6601 - accuracy: 0.4600 - val_loss: 0.6723 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6628 - accuracy: 0.4600 - val_loss: 0.6724 - val_accuracy: 0.4200
Epoch 1/5
2/2 [==============================] - 0s 83ms/step - loss: 0.6914 - accuracy: 0.4600 - val_loss: 0.6788 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6781 - accuracy: 0.4600 - val_loss: 0.6820 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6577 - accuracy: 0.4600 - val_loss: 0.6981 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 14ms/step - loss: 0.6619 - accuracy: 0.4600 - val_loss: 0.6856 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6490 - accuracy: 0.4600 - val_loss: 0.6745 - val_accuracy: 0.4200
[Trial complete]
[Trial summary]
 |-Trial ID: 9fbfbee51e24105a949d6a7e41aeb370
 |-Score: 0.41999998688697815
 |-Best step: 0
 > Hyperparameters:
 |-learning_rate: 0.01
 |-units: 480
Epoch 1/5
2/2 [==============================] - 0s 86ms/step - loss: 0.6880 - accuracy: 0.4600 - val_loss: 0.6903 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6876 - accuracy: 0.4600 - val_loss: 0.6899 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6872 - accuracy: 0.4600 - val_loss: 0.6896 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6871 - accuracy: 0.4600 - val_loss: 0.6893 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6867 - accuracy: 0.4600 - val_loss: 0.6890 - val_accuracy: 0.4200
Epoch 1/5
2/2 [==============================] - 0s 82ms/step - loss: 0.6938 - accuracy: 0.4600 - val_loss: 0.6934 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6935 - accuracy: 0.4600 - val_loss: 0.6931 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6932 - accuracy: 0.4600 - val_loss: 0.6928 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 21ms/step - loss: 0.6929 - accuracy: 0.4600 - val_loss: 0.6927 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6927 - accuracy: 0.4600 - val_loss: 0.6924 - val_accuracy: 0.4200
Epoch 1/5
2/2 [==============================] - 0s 85ms/step - loss: 0.6916 - accuracy: 0.4600 - val_loss: 0.6792 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6913 - accuracy: 0.4600 - val_loss: 0.6792 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6912 - accuracy: 0.4600 - val_loss: 0.6792 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6908 - accuracy: 0.4600 - val_loss: 0.6792 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6907 - accuracy: 0.4600 - val_loss: 0.6792 - val_accuracy: 0.4200
[Trial complete]
[Trial summary]
 |-Trial ID: 401da923f22079c697f3a3d8393440e2
 |-Score: 0.41999998688697815
 |-Best step: 0
 > Hyperparameters:
 |-learning_rate: 0.0001
 |-units: 160
Epoch 1/5
2/2 [==============================] - 0s 83ms/step - loss: 0.6898 - accuracy: 0.4600 - val_loss: 0.6866 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6875 - accuracy: 0.4600 - val_loss: 0.6856 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6858 - accuracy: 0.4600 - val_loss: 0.6840 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6846 - accuracy: 0.4600 - val_loss: 0.6825 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 11ms/step - loss: 0.6830 - accuracy: 0.4600 - val_loss: 0.6814 - val_accuracy: 0.4200
Epoch 1/5
2/2 [==============================] - 0s 84ms/step - loss: 0.7053 - accuracy: 0.4600 - val_loss: 0.7105 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 13ms/step - loss: 0.7000 - accuracy: 0.4600 - val_loss: 0.7057 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6960 - accuracy: 0.4600 - val_loss: 0.7012 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6927 - accuracy: 0.4600 - val_loss: 0.6971 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 13ms/step - loss: 0.6902 - accuracy: 0.4600 - val_loss: 0.6936 - val_accuracy: 0.4200
Epoch 1/5
2/2 [==============================] - 0s 84ms/step - loss: 0.6967 - accuracy: 0.4600 - val_loss: 0.6918 - val_accuracy: 0.4200
Epoch 2/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6946 - accuracy: 0.4600 - val_loss: 0.6902 - val_accuracy: 0.4200
Epoch 3/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6930 - accuracy: 0.4600 - val_loss: 0.6892 - val_accuracy: 0.4200
Epoch 4/5
2/2 [==============================] - 0s 14ms/step - loss: 0.6915 - accuracy: 0.4600 - val_loss: 0.6885 - val_accuracy: 0.4200
Epoch 5/5
2/2 [==============================] - 0s 12ms/step - loss: 0.6903 - accuracy: 0.4600 - val_loss: 0.6874 - val_accuracy: 0.4200
[Trial complete]
[Trial summary]
 |-Trial ID: 4eeb656ab8b77a7734ab050a3c3a87cc
 |-Score: 0.41999998688697815
 |-Best step: 0
 > Hyperparameters:
 |-learning_rate: 0.001
 |-units: 96
```
